### ISSUE TITLE
Add Cell Editing to TRC

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/teselagen-react-components#289]
- [x] powers the upload wizard https://github.com/TeselaGen/teselagen-react-components/issues/293
- [x] add smart increment on cell drag handle (cases described below) (for string and number fields only!!!)

Dragging just 1 cell with nothing before it (same as normal): 

<img width="161" alt="image" src="https://user-images.githubusercontent.com/2730609/199828309-b828d739-799b-4058-9692-1743ac862c0e.png">
becomes 
<img width="151" alt="image" src="https://user-images.githubusercontent.com/2730609/199828342-0cfeeb71-ece5-4d17-8fdc-b581f76bcb0c.png">

Dragging more than one cell incrementing: 
<img width="217" alt="image" src="https://user-images.githubusercontent.com/2730609/199828047-323334fa-3f69-40f7-ac9e-e21c06313283.png">
becomes 
<img width="178" alt="image" src="https://user-images.githubusercontent.com/2730609/199828078-971d61b5-6f46-4f4f-8adb-8df181fd5b12.png">

Dragging more than one cell incrementing with text and 0 before: 
<img width="155" alt="image" src="https://user-images.githubusercontent.com/2730609/199828219-7f729bc5-4c27-4518-adc4-e1796798ad06.png">
becomes
<img width="146" alt="image" src="https://user-images.githubusercontent.com/2730609/199828261-1eac2809-f294-4500-9591-5e443798ca31.png">

Dragging just one cell with increment before: 
<img width="187" alt="image" src="https://user-images.githubusercontent.com/2730609/199828738-4c3288bc-65b1-4719-993f-066e62c331bd.png">
becomes
<img width="172" alt="image" src="https://user-images.githubusercontent.com/2730609/199828774-d2fda402-5f3a-4561-8105-be9f64bc5b90.png">

 
- [x] make sure comma seperated vals can be pasted in (copied direct from CSV) need to allow for commas in quotes
- [x] support addition of rows when pasting in data that overflows the bottom of the table
- [x] validation needs to be rerun for affected rows on paste (not sure why it's not already?) (seems like it is in certain cases --> repro - upload affinity tags csv and copy sequence from type row to another row)
- [x] make sure download of files from file list is working
- [x] make sure remove rows works on the last row if it is the only row selected
- [x] add an `Add 10 Rows` button to the bottom of the table 
   - [x] make sure it still shows up when there is no data
   - [x] make sure it doesn't show up when `Show only rows with errors` is enabled

- [x] when deleting rows, validation needs to be removed for those rows
- [x] add cell selection abilities
- [x] add click to edit cell
- [x] add dropdown editable cells 
  - [x] dropdown cell should have a little click to edit icon: 
  
<img width="101" alt="image" src="https://user-images.githubusercontent.com/2730609/196796298-6fe0daab-bb8d-48a0-8248-5fae631055ff.png">

<img width="126" alt="image" src="https://user-images.githubusercontent.com/2730609/196557002-316763fb-aaf6-40b8-bb03-c6f57f3af207.png">

- [x] add bottom right drag to copy cell to cells below functionality
<img width="268" alt="image" src="https://user-images.githubusercontent.com/2730609/196556540-3d21b0bb-2b4f-49cb-8d76-8a5cf8cf30bd.png">

- [x] make sure bottom right drag works with boolean column

- [x] add numeric input 
- [x] support paste functionality 

- [x] add column auto validation/formatting 

  - [x] drop-down/boolean/numeric column should auto format malformed incoming data 
  
  - [x] malformed data that can't be auto formatted should display as a red cell

  - [x] allow passing additional validation/formatting functions on the column schema

- [x] dragging the cell drag handle should allow the table to scroll if necessary 
- [x] take out the padding on the dropdown cell when it is in edit mode
- [x] add a tiny margin right on the table when in cell editing mode to prevent unnecessary horizontal scrollbar when selected (caused by cell dropdown dragger)
- [x] Support selection of multiple cells
- [x] support copy of multiple cells
- [x] support addition of rows
- [x] start single cell edit on hitting enter
- [x] do NOT send edit action if no edit was actually made to the cells
- [x] fix dropdown styling(?) weirdness: 
https://user-images.githubusercontent.com/2730609/199064687-9739bfc4-9769-4a46-8624-fde46d4e1286.mov
- [x] add cell delete + cell cut functionality
- [x] add tests for all the above bullet points (where applicable)
Stretch Goals:
- [x] allow cell drag to occur across multiple columns if multiple columns are selected in a contiguous group

**Comment by tgreen7** [comment]
pasting logic:

1. If there is a single thing in clipboard (no newlines and no tabs), paste that into every selected cell
2. try to paste in the same layout that the copy was in should match cell to cell where possible in selections. extra cells from copy that are not in new selection will be ignored.
3.  if only a single cell is selected when pasting then the copied format should try to paste all cells in same format until it runs of edge

**Comment by tnrich** [comment]
Closing this as it has been completed!
