### ISSUE TITLE
Table UI Changes

### ISSUE THREAD

**Issue by tgreen7** [TeselaGen/teselagen-react-components#297]
- [x] improve the boolean field to use more friendly icons (we'll need a couple custom icons perhaps) instead of True/False  (this will break some tests but should be easily correctable
<img width="148" alt="image" src="https://user-images.githubusercontent.com/2730609/200926415-c43b551d-276d-42a3-a012-94f9dd6b69fa.png">

- [x] allow table column headers to show a description upon hover (if a description is passed in the schema field)
- [x] do not show the column header tooltip if there is not overflow 
- [x] make sure the overflow tooltip does not get repeated upon dragging/resizing the column header

**Comment by tnrich** [comment]
@tgreen7 these have all been completed, right?
